version: '3'

services:
  apidb:
    container_name: osm-apidb
    image: yamap-osm-apidb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB_SCHEMA=${POSTGRES_DB_SCHEMA}
    volumes: 
      - ./../../data/apidb/:/var/lib/postgresql/data
    env_file:
      - ./../../env/apidb.env
    ports:
      - 5432:5432
    networks:
      - apidb

networks:
  apidb: